name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '*/10 1 * * 1'
    - cron:  '*/10 2 * * 2'
    - cron:  '*/10 3 * * 3'
    - cron:  '*/10 4 * * 4'
    - cron:  '*/10 0 * * 5'
    - cron:  '*/10 3 * * 6'
    - cron:  '*/10 1 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: Roll dice
        run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV && echo $GITHUB_ENV
        shell: bash
        
      - if: ${{ env.PROCEED == '0' }}
        name: Cancelling
        uses: andymckay/cancel-action@0.2

      - if: ${{ env.PROCEED == '0' }}
        name: Waiting for cancellation
        run: sleep 60
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
